---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.service.name }}
  namespace: {{ .Values.backend.namespace }}
  labels:
    app: {{ .Values.backend.labels.app }}
spec:
  selector:
    app: {{ .Values.backend.labels.app }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
  type: ClusterIP
